/*
**
** The C code is generated by [ATS/Postiats-0-4-1]
** The starting compilation time is: 2026-1-5:  1h:29m
**
*/

/*
** include runtime header files
*/
#ifndef _ATS_CCOMP_HEADER_NONE_
#include "pats_ccomp_config.h"
#include "pats_ccomp_basics.h"
#include "pats_ccomp_typedefs.h"
#include "pats_ccomp_instrset.h"
#include "pats_ccomp_memalloc.h"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_memalloca.h"
#include "pats_ccomp_exception.h"
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_HEADER_NONE_ */


/*
** include prelude cats files
*/
#ifndef _ATS_CCOMP_PRELUDE_NONE_
//
#include "prelude/CATS/basics.cats"
#include "prelude/CATS/integer.cats"
#include "prelude/CATS/pointer.cats"
#include "prelude/CATS/integer_long.cats"
#include "prelude/CATS/integer_size.cats"
#include "prelude/CATS/integer_short.cats"
#include "prelude/CATS/bool.cats"
#include "prelude/CATS/char.cats"
#include "prelude/CATS/float.cats"
#include "prelude/CATS/integer_ptr.cats"
#include "prelude/CATS/integer_fixed.cats"
#include "prelude/CATS/memory.cats"
#include "prelude/CATS/string.cats"
#include "prelude/CATS/strptr.cats"
//
#include "prelude/CATS/fprintf.cats"
//
#include "prelude/CATS/filebas.cats"
//
#include "prelude/CATS/list.cats"
#include "prelude/CATS/option.cats"
#include "prelude/CATS/array.cats"
#include "prelude/CATS/arrayptr.cats"
#include "prelude/CATS/arrayref.cats"
#include "prelude/CATS/matrix.cats"
#include "prelude/CATS/matrixptr.cats"
//
#endif /* _ATS_CCOMP_PRELUDE_NONE_ */
/*
** for user-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER_
//
#include _ATS_CCOMP_PRELUDE_USER_
//
#endif /* _ATS_CCOMP_PRELUDE_USER_ */
/*
** for user2-supplied prelude
*/
#ifdef _ATS_CCOMP_PRELUDE_USER2_
//
#include _ATS_CCOMP_PRELUDE_USER2_
//
#endif /* _ATS_CCOMP_PRELUDE_USER2_ */

/*
staload-prologues(beg)
*/
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/stat.sats: 1390(line=36, offs=1) -- 1440(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/stat.cats"
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/stdio.sats: 1390(line=36, offs=1) -- 1437(line=39, offs=3)
*/

#include \
"libats/libc/CATS/stdio.cats"
/*
/opt/homebrew/Cellar/ats2-postiats/0.4.2_1/lib/ats2-postiats-0.4.2/libats/libc/SATS/sys/types.sats: 1390(line=36, offs=1) -- 1441(line=39, offs=3)
*/

#include \
"libats/libc/CATS/sys/types.cats"
/*
staload-prologues(end)
*/
/*
typedefs-for-tyrecs-and-tysums(beg)
*/
/*
typedefs-for-tyrecs-and-tysums(end)
*/
/*
dynconlst-declaration(beg)
*/
/*
dynconlst-declaration(end)
*/
/*
dyncstlst-declaration(beg)
*/
ATSdyncst_mac(atspre_print_string)
ATSdyncst_mac(atspre_print_newline)
ATSdyncst_mac(atspre_g1int_add_int)
ATSdyncst_mac(atspre_print_int)
/*
dyncstlst-declaration(end)
*/
/*
dynvalist-implementation(beg)
*/
/*
dynvalist-implementation(end)
*/
/*
exnconlst-declaration(beg)
*/
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
ATSextern()
atsvoid_t0ype
the_atsexncon_initize
(
  atstype_exnconptr d2c, atstype_string exnmsg
) ;
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
/*
exnconlst-declaration(end)
*/
/*
extypelst-declaration(beg)
*/
/*
extypelst-declaration(end)
*/
/*
assumelst-declaration(beg)
*/
#ifndef _ATS_CCOMP_ASSUME_CHECK_NONE_
#endif // #ifndef(_ATS_CCOMP_ASSUME_CHECK_NONE_)
/*
assumelst-declaration(end)
*/
#if(0)
ATSextern()
atsvoid_t0ype
mainats_0_void() ;
#endif // end of [QUALIFIED]

/*
/Users/zach/devel/zenon/test/simple-ats/hello.dats: 91(line=8, offs=7) -- 246(line=13, offs=2)
*/
/*
local: 
global: mainats_0_void$0$0(level=0)
local: 
global: 
*/
ATSextern()
atsvoid_t0ype
mainats_0_void()
{
/* tmpvardeclst(beg) */
// ATStmpdec_void(tmpret0) ;
// ATStmpdec_void(tmp1) ;
// ATStmpdec_void(tmp2) ;
// ATStmpdec_void(tmp3) ;
// ATStmpdec_void(tmp4) ;
ATStmpdec(tmp5, atstkind_t0ype(atstype_int)) ;
// ATStmpdec_void(tmp6) ;
// ATStmpdec_void(tmp7) ;
/* tmpvardeclst(end) */
ATSfunbody_beg()
/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 85(line=8, offs=1) -- 246(line=13, offs=2)
*/
ATSINSflab(__patsflab_main_0_void):
/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 96(line=8, offs=12) -- 246(line=13, offs=2)
*/
/*
letpush(beg)
*/
/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 109(line=9, offs=12) -- 147(line=9, offs=50)
*/
ATSINSmove_void(tmp1, atspre_print_string(ATSPMVstring("Testing simple ATS2 build"))) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 109(line=9, offs=12) -- 147(line=9, offs=50)
*/
ATSINSmove_void(tmp2, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 159(line=10, offs=12) -- 188(line=10, offs=41)
*/
ATSINSmove_void(tmp3, atspre_print_string(ATSPMVstring("Hello from ATS2!"))) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 159(line=10, offs=12) -- 188(line=10, offs=41)
*/
ATSINSmove_void(tmp4, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 199(line=11, offs=11) -- 206(line=11, offs=18)
*/
ATSINSmove(tmp5, atspre_g1int_add_int(ATSPMVi0nt(10), ATSPMVi0nt(20))) ;

/*
letpush(end)
*/

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 218(line=12, offs=12) -- 244(line=12, offs=38)
*/
ATSINSmove_void(tmp6, atspre_print_string(ATSPMVstring("10 + 20 = "))) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 218(line=12, offs=12) -- 244(line=12, offs=38)
*/
ATSINSmove_void(tmp7, atspre_print_int(tmp5)) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 218(line=12, offs=12) -- 244(line=12, offs=38)
*/
ATSINSmove_void(tmpret0, atspre_print_newline()) ;

/*
emit_instr: loc0 = /Users/zach/devel/zenon/test/simple-ats/hello.dats: 96(line=8, offs=12) -- 246(line=13, offs=2)
*/
/*
INSletpop()
*/
ATSfunbody_end()
ATSreturn_void(tmpret0) ;
} /* end of [mainats_0_void] */

/*
** for initialization(dynloading)
*/
ATSdynloadflag_minit(_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynloadflag) ;
ATSextern()
atsvoid_t0ype
_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynload()
{
ATSfunbody_beg()
ATSdynload(/*void*/)
ATSdynloadflag_sta(
_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynloadflag
) ;
ATSif(
ATSCKiseqz(
_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynloadflag
)
) ATSthen() {
ATSdynloadset(_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynloadflag) ;
/*
dynexnlst-initize(beg)
*/
/*
dynexnlst-initize(end)
*/
} /* ATSendif */
ATSfunbody_end()
ATSreturn_void(tmpret_void) ;
} /* end of [*_dynload] */

/*
** the ATS runtime
*/
#ifndef _ATS_CCOMP_RUNTIME_NONE_
#include "pats_ccomp_runtime.c"
#include "pats_ccomp_runtime_memalloc.c"
#ifndef _ATS_CCOMP_EXCEPTION_NONE_
#include "pats_ccomp_runtime2_dats.c"
#ifndef _ATS_CCOMP_RUNTIME_TRYWITH_NONE_
#include "pats_ccomp_runtime_trywith.c"
#endif /* _ATS_CCOMP_RUNTIME_TRYWITH_NONE_ */
#endif // end of [_ATS_CCOMP_EXCEPTION_NONE_]
#endif /* _ATS_CCOMP_RUNTIME_NONE_ */

/*
** the [main] implementation
*/
int
main
(
int argc, char **argv, char **envp
) {
int err = 0 ;
_057_Users_057_zach_057_devel_057_zenon_057_test_057_simple_055_ats_057_hello_056_dats__dynload() ;
ATSmainats_0_void(err) ;
return (err) ;
} /* end of [main] */

/* ****** ****** */

/* end-of-compilation-unit */
